### ISSUE TITLE
S3: Required calls

### ISSUE THREAD

**Issue by MariusDieckmann** [ArunaStorage/proxy#19]
The following subset of S3 should be implemented in a first version of the API.

- [x] ListBucket
- [x] CreateBucket
- [ ]  DeleteBucket
- [ ]  HeadBucket
- [x]  PutObject
- [x]  GetObject
- [x]  CreateMultipartUpload
- [x]  UploadPart
- [x]  CompleteMultipartUpload
- [ ]  AbortMultipartUpload
- [ ]  ListObjects
- [x] #32
- [ ]  ListParts
- [ ]  PutObjectTagging
- [ ]  DeleteObject
- [ ]  GetObjectTagging
- [x]  HeadObject
- [ ]  UploadPartCopy

**Comment by mzur** [comment]
From my perspective as a user, ListObjectV2 would be the most important operation that is still missing.
